// supabase/functions/generate-subtasks/index.ts
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { corsHeaders } from "../_shared/cors.ts";

// Mock AI API call
const callGenerativeAI = async (prompt: string): Promise<string[]> => {
  console.log("Calling Mock AI with prompt:", prompt);
  // In a real scenario, this would be a fetch request to a service like OpenAI or Google AI
  return new Promise(resolve => {
    setTimeout(() => {
      const subtasks = [
        "Sub-task 1 generated by AI.",
        "Sub-task 2 generated by AI.",
        "Sub-task 3 generated by AI.",
      ];
      resolve(subtasks);
    }, 1000);
  });
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { prompt } = await req.json();
    const subtasks = await callGenerativeAI(prompt);

    return new Response(JSON.stringify({ subtasks }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 400,
    });
  }
});
